version: "3.7"

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.0.1
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
