version: "3.7"

services:

  authentication-service:
    image: frogdevelopment/authentication-service:master
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - pond
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-dico-entries-service:
    image: frogdevelopment/nihongo-dico-entries-service:master
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - pond
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-dico-sentences-service:
    image: frogdevelopment/nihongo-dico-sentences-service:master
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      - authentication-service
    networks:
      - pond
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-lessons-service:
    image: frogdevelopment/nihongo-lessons-service:master
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      - authentication-service
    networks:
      - pond
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-dico-web:
    image: frogdevelopment/nihongo-dico-web:latest
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == small
    depends_on:
      - nihongo-dico-entries-service
      - nihongo-dico-sentences-service
    networks:
      - pond
    environment:
      VIRTUAL_HOST: www.nihongo-dico.frog-development.com
      LETSENCRYPT_HOST: www.nihongo-dico.frog-development.com

  frog-manager-web:
    image: frogdevelopment/frog-manager-web:feature-nginx_conf
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == small
    depends_on:
      - nihongo-dico-entries-service
      - nihongo-dico-sentences-service
      - nihongo-lessons-service
    networks:
      - pond
    environment:
      VIRTUAL_HOST: manager.frog-development.com
      LETSENCRYPT_HOST: manager.frog-development.com

secrets:
  frog_admin_user:
    external: true
  frog_admin_password:
    external: true

networks:
  pond:
    external: true
    name: pond
