version: "3.7"

services:

  authentication-service:
    image: frogdevelopment/authentication-service:master
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - nihongo
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-dico-entries-service:
    image: frogdevelopment/nihongo-dico-entries-service:master
    deploy:
        mode: replicated
        replicas: 0
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - nihongo
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-dico-sentences-service:
    image: frogdevelopment/nihongo-dico-sentences-service:feat_download_before
    deploy:
        mode: replicated
        replicas: 0
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      - authentication-service
    networks:
      - nihongo
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

  nihongo-lessons-service:
    image: frogdevelopment/nihongo-lessons-service:master
    deploy:
        mode: replicated
        replicas: 0
        placement:
          constraints:
            - node.labels.size == large
    healthcheck:
      test: ["CMD", "curl", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      - authentication-service
    networks:
      - nihongo
    secrets:
      - frog_admin_user
      - frog_admin_password
    environment:
      TZ: Europe/Paris

secrets:
  frog_admin_user:
    external: true
  frog_admin_password:
    external: true

networks:
  nihongo:
    external: true
    name: nihongo
