version: "3.7"

services:

  nihongo-dico-web:
    image: frognihongo/nihongo-dico-web:latest
    deploy:
        mode: replicated
        replicas: 0
        placement:
          constraints:
            - node.labels.size == small
    networks:
      - nihongo
    environment:
      VIRTUAL_HOST: www.nihongo-dico.frog-development.com
      LETSENCRYPT_HOST: www.nihongo-dico.frog-development.com

  frog-manager-web:
    image: frognihongo/frog-manager-web:latest
    deploy:
        mode: replicated
        replicas: 0
        placement:
          constraints:
            - node.labels.size == small
    networks:
      - nihongo
    environment:
      VIRTUAL_HOST: manager.nihongo.frog-development.com
      LETSENCRYPT_HOST: manager.nihongo.frog-development.com

networks:
  nihongo:
    external: true
    name: nihongo
