version: "3.7"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine-0.7.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == small
    ports:
      - 80:80
      - 443:443
    networks:
      - pond
    volumes:
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    logging:
      options:
        max-size: "50k"
        max-file: "2"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == small
    depends_on:
      - nginx-proxy
    networks:
      - pond
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: "50k"
        max-file: "2"

  postgres:
    image: groonga/pgroonga:2.2.2-alpine-12-slim
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == large
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 9173:5432
    networks:
      - pond
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgAdmin:
    image: dpage/pgadmin4:4.16
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.size == small
    ports:
      - 90:80
    depends_on:
      - postgres
    networks:
      - pond
    environment:
      PGADMIN_DEFAULT_EMAIL: ${FROG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${FROG_ADMIN_PWD}
      VIRTUAL_HOST: pgadmin.frog-development.com
      LETSENCRYPT_HOST: pgadmin.frog-development.com
      LETSENCRYPT_EMAIL: ${FROG_ADMIN_EMAIL}

volumes:
  postgres_data:
  dhparam:
  vhost:
  html:
  certs:

networks:
  pond:
    external: true
    name: pond
