version: "3.7"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.7.0
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frog_tools
      - frog_ms
    logging:
      options:
        max-size: "50k"
        max-file: "2"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.11.2
    container_name: nginx-proxy-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: "50k"
        max-file: "2"
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - frog_tools
      - frog_ms

  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    restart: always
    depends_on:
      - mariadb
      - nginx-proxy
      - nginx-proxy-letsencrypt
    expose:
      - 8080
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - mariadb:mysql
    environment:
      TZ: Europe/Paris
      VIRTUAL_HOST: jenkins.frog-development.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: jenkins.frog-development.com
      LETSENCRYPT_EMAIL: frog-development-it@gmail.com
    logging:
      options:
        max-size: "100k"
        max-file: "4"

  mariadb:
    image: mariadb:10.4.6
    container_name: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jenkins_database
    logging:
      options:
        max-size: "50k"
        max-file: "2"

volumes:
  mariadb:
  jenkins_home:
  dhparam:
  vhost:
  html:
  certs:

networks:
  default:
      name: frog_tools
  frog_ms:
    driver: bridge
    external: true
    name: frog_ms
  frog_tools:
    driver: bridge
    name: frog_tools
