kind: Service
apiVersion: v1
metadata:
  name: service-config
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      selector:
        app: service-config
      ports:
        - protocol: TCP
        port: 8080
      type: ClusertIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-config
spec:
  selector:
    matchLabels:
      app: service-config
  replicas: 3
  template:
    metadata:
      labels:
        app: service-config
    spec:
      containers:
        name: service-config
        image: frogdevelopment/service-config:master
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
