version: "3.7"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.7.0
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      TZ: Europe/Paris

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.11.2
    container_name: nginx-proxy-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Paris
      NGINX_PROXY_CONTAINER: nginx-proxy

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.11.1
    container_name: artifactory
    restart: always
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
    expose:
      - 8081
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      TZ: Europe/Paris
      VIRTUAL_HOST: artifactory.frog-development.com
      LETSENCRYPT_HOST: artifactory.frog-development.com
      LETSENCRYPT_EMAIL: postmaster@frog-development.com
      EXTRA_JAVA_OPTIONS: '-server -Xms512m -Xmx4g -Xss256k -XX:+UseG1GC'

volumes:
  dhparam:
  vhost:
  html:
  certs:
  artifactory_data:
